# Simple Hugging Face Downloader Configuration
# Usage: python src/main.py cmd=download download=hf

name: hf
save_dir: models/

items:
  # - name: wav2vec2-base
  #   repo: facebook/wav2vec2-base
  #   type: model
  #   revision: main
  #   save: wav2vec2
  
  # - name: bert-base
  #   repo: bert-base-uncased
  #   type: model
  #   revision: main
  #   save: bert
  
  # - name: bert-tokenizer
  #   repo: bert-base-uncased
  #   type: tokenizer
  #   revision: main
  #   save: tokenizer
  
  # - name: phi4-model
  #   repo: microsoft/Phi-4-multimodal-instruct
  #   type: model
  #   revision: main
  #   save: phi4

  - name: wav2vec2-conformer
    repo: facebook/wav2vec2-conformer-rel-pos-large
    type: model
    revision: main
    save: wav2vec2-conformer
