defaults:
  - data: icnale_base
  - model: crossmodal_base
  - task: classification
  - train: base
  - eval: base
  - pipeline: base

seed: 42
output_dir: ${hydra:run.dir}
cmd: train # train | eval | pipeline | download