from __future__ import annotations
from typing import Protocol, Dict
import torch

class Metric(Protocol):
    def update(self, preds: torch.Tensor, target: torch.Tensor) -> None: ...
    def compute(self) -> Dict[str, float]: ...
    def reset(self) -> None: ...