# Optimizer settings
optimizer: adamw
lr: 1e-4
weight_decay: 0.01

# Training schedule
epochs: 20
batch: 1
num_workers: 1

# HuggingFace Trainer specific settings
hf_trainer:
  # Core training arguments
  output_dir: ./outputs/hf_training
  overwrite_output_dir: true
  
  # Training parameters
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  
  # Learning rate and scheduling
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_steps: 100
  lr_scheduler_type: "linear"
  
  # Training duration
  num_train_epochs: 20
  max_steps: -1  # If set to positive, overrides num_train_epochs
  
  # Optimization
  fp16: false
  bf16: true  # Use bfloat16 for better numerical stability
  tf32: true
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  
  # Gradient clipping
  max_grad_norm: 1.0
  
  # Evaluation
  evaluation_strategy: "no" # Options: "no", "steps", "epoch"
  eval_steps: null
  eval_accumulation_steps: null
  
  # Logging
  logging_strategy: "steps"
  logging_steps: 10
  logging_first_step: true

  # GPU/Host memory logging
  log_gpu_memory: true
  log_mem_every_n_steps: 1  # set >1 to throttle
  log_host_memory: true
  
  # Saving
  save_strategy: "steps"
  save_steps: 1000
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  
  # Early stopping
  early_stopping_patience: 5
  early_stopping_threshold: 0.001
  
  # Reproducibility
  seed: 42
  data_seed: 42
  
  # Data loading
  dataloader_num_workers: 1
  dataloader_pin_memory: false
  dataloader_persistent_workers: false
  
  # Distributed training
  ddp_find_unused_parameters: true
  ddp_bucket_cap_mb: 25
  ddp_broadcast_buffers: false
  
  # Memory optimization
  dataloader_drop_last: true
  remove_unused_columns: true
  
  # Reporting
  report_to: "tensorboard"
  logging_dir: "./outputs/hf_training/logs"
  disable_tqdm: true
  
  # Advanced settings
  push_to_hub: false
  resume_from_checkpoint: null
  ignore_data_skip: false
  
  # Model saving format
  save_safetensors: true
  
  # Deep Speed
  deepspeed_enabled: false
  deepspeed: "configs/deepspeed/zero2_base.json"
